# Generated by Django 5.2.5 on 2025-10-07 06:02

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=users.models.generate_uuid_hex, editable=False, primary_key=True, serialize=False),
        ),
    ]
