# Generated by Django 5.2.5 on 2025-09-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_id_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='uid',
            new_name='id',
        ),
    ]
