# Generated by Django 5.2.5 on 2025-09-20 08:49

import books.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bookCategory',
            fields=[
                ('name', models.CharField(db_index=True, default='null', max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(default=books.models.generate_uuid_hex, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('auther', models.CharField(default='Not defined', max_length=50)),
                ('addr', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='shelf.shelf', validators=[books.models.validate_book_addr])),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookcategory', validators=[books.models.validate_catagory])),
            ],
        ),
        migrations.CreateModel(
            name='issueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
