# Generated by Django 5.2.5 on 2025-08-24 10:50

import books.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookcategory', validators=[books.models.validate_catagory]),
        ),
        migrations.AlterField(
            model_name='book',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
