# Generated by Django 5.2.5 on 2025-08-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('Address', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
            ],
        ),
    ]
