# Generated by Django 5.2.5 on 2025-10-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('addr', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, verbose_name='Address')),
                ('qunt', models.IntegerField(default=0, verbose_name='Quantity')),
            ],
        ),
    ]
